# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f483e0a00e90319f1305c4b12743209dbdcc7700f20c33fe4ee35a1a295f5dc7ca21117e27ef7a4cff29af843ef238bd6bdbf6bbb601f52ba915c5c76b1b34de

test:
  secret_key_base: 8c28cd1b122392978d6ac30dd13e0b803f64f2c48b316df1155caa02419fd1d5ccb925b9e3792510885ea4fed56cf3071f5c3f92695c97e40fbaec6d0386820d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
